export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_FAILED = "FETCH_MOVIES_FAILED";

export const FETCH_MOVIES_DETAIL_SUCCESS = "FETCH_MOVIES_DETAIL_SUCCESS";
export const FETCH_MOVIES_DETAIL_FAILED = "FETCH_MOVIES_DETAIL_FAILED";

export const FETCH_MOVIES_VIDEO_SUCCESS = "FETCH_MOVIES_VIDEO_SUCCESS";
export const FETCH_MOVIES_VIDEO_FAILED = "FETCH_MOVIES_VIDEO_FAILED";

export const FETCH_TOP_RATED_SUCCESS = "FETCH_TOP_RATED_SUCCESS";
export const FETCH_TOP_RATED_FAILED = "FETCH_TOP_RATED_FAILED";

export const FETCH_PERSON_SUCCESS = "FETCH_PERSON_SUCCESS";
export const FETCH_PERSON_FAILED = "FETCH_PERSON_FAILED";

export const FETCH_PERSON_DETAIL_SUCCESS = "FETCH_PERSON_DETAIL_SUCCESS";
export const FETCH_PERSON_DETAIL_FAILED = "FETCH_PERSON_DETAIL_FAILED";

export const FETCH_GENRE_SUCCESS = "FETCH_GENRE_SUCCESS";
export const FETCH_GENRE_FAILED = "FETCH_GENRE_FAILED";

export const FETCH_NOWPLAYING_SUCCESS = "FETCH_NOWPLAYING_SUCCESS";
export const FETCH_NOWPLAYING_FAILED = "FETCH_NOWPLAYING_FAILED";